"use client";

import { FormEvent, useEffect, useState } from "react";
import api from "@/lib/api";

type Department = { id: number; name: string; code: string; description?: string };
type Course = { id: number; name: string; code: string; duration: number; department?: Department };
type Subject = { id: number; name: string; code: string; credits: number; semester: string; description?: string; course?: Course };
type Tab = "departments" | "courses" | "subjects";

const semesters = ["SEMESTER_1","SEMESTER_2","SEMESTER_3","SEMESTER_4","SEMESTER_5","SEMESTER_6","SEMESTER_7","SEMESTER_8"];
const inputClass = "w-full rounded-lg border border-slate-700 bg-slate-800 px-4 py-2.5 text-white outline-none focus:border-blue-500";

export default function AcademicPage() {
  const [departments,setDepartments]=useState<Department[]>([]),[courses,setCourses]=useState<Course[]>([]),[subjects,setSubjects]=useState<Subject[]>([]);
  const [tab,setTab]=useState<Tab>("departments"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
  const [department,setDepartment]=useState({name:"",code:"",description:""});
  const [course,setCourse]=useState({departmentId:"",name:"",code:"",duration:"4"});
  const [subject,setSubject]=useState({courseId:"",name:"",code:"",credits:"4",semester:"SEMESTER_1",description:""});

  useEffect(()=>{load();},[]);
  async function load(){setLoading(true);setError("");try{const [d,c,s]=await Promise.all([api.get("/academic/departments"),api.get("/academic/courses"),api.get("/academic/subjects")]);setDepartments(Array.isArray(d.data)?d.data:[]);setCourses(Array.isArray(c.data)?c.data:[]);setSubjects(Array.isArray(s.data)?s.data:[]);}catch(e:any){setError(e?.response?.data?.message||"Failed to load academic data.");}finally{setLoading(false);}}
  function add(){setError("");setSuccess("");if(tab==="courses"&&departments.length&&!course.departmentId)setCourse(x=>({...x,departmentId:String(departments[0].id)}));if(tab==="subjects"&&courses.length&&!subject.courseId)setSubject(x=>({...x,courseId:String(courses[0].id)}));setShowForm(true);}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setSuccess("");try{if(tab==="departments"){await api.post("/academic/departments",department);setDepartment({name:"",code:"",description:""});setSuccess("Department created.");}else if(tab==="courses"){if(!course.departmentId)throw new Error("Select a department.");await api.post("/academic/courses",{departmentId:Number(course.departmentId),name:course.name,code:course.code,duration:Number(course.duration)});setCourse({departmentId:course.departmentId,name:"",code:"",duration:"4"});setSuccess("Course created.");}else{if(!subject.courseId)throw new Error("Select a course.");await api.post("/academic/subjects",{courseId:Number(subject.courseId),name:subject.name,code:subject.code,credits:Number(subject.credits),semester:subject.semester,description:subject.description||undefined});setSubject(x=>({...x,name:"",code:"",description:""}));setSuccess("Subject created.");}setShowForm(false);await load();}catch(e:any){setError(e?.response?.data?.message||e?.message||"Could not save changes.");}finally{setSaving(false);}}
  const q=search.toLowerCase().trim();
  const ds=departments.filter(x=>`${x.name} ${x.code} ${x.description||""}`.toLowerCase().includes(q));
  const cs=courses.filter(x=>`${x.name} ${x.code} ${x.department?.name||""}`.toLowerCase().includes(q));
  const ss=subjects.filter(x=>`${x.name} ${x.code} ${x.semester} ${x.course?.name||""}`.toLowerCase().includes(q));
  const label=tab==="departments"?"Department":tab==="courses"?"Course":"Subject";
  return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div><h1 className="text-2xl font-bold">Academic Management</h1><p className="mt-1 text-sm text-slate-400">Live departments, courses and subjects</p></div><button onClick={load} className="rounded-lg border border-slate-700 px-4 py-2 text-sm hover:bg-slate-800">Refresh</button></div></header><div className="mx-auto max-w-7xl px-6 py-8">
  {error&&<div className="mb-4 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{Array.isArray(error)?error.join(", "):error}</div>}{success&&<div className="mb-4 rounded-xl border border-green-500/20 bg-green-500/10 px-4 py-3 text-sm text-green-300">{success}</div>}
  <div className="grid gap-4 sm:grid-cols-3">{([["departments","Departments",departments.length],["courses","Courses",courses.length],["subjects","Subjects",subjects.length]] as [Tab,string,number][]).map(([k,t,n])=><button key={k} onClick={()=>{setTab(k);setShowForm(false);setSearch("")}} className={`rounded-2xl border p-5 text-left ${tab===k?"border-blue-500 bg-blue-500/10":"border-slate-800 bg-slate-900 hover:border-slate-700"}`}><span className="text-sm text-slate-400">{t}</span><div className="mt-2 text-3xl font-bold">{n}</div><span className="mt-2 block text-xs text-blue-400">Manage {t.toLowerCase()} →</span></button>)}</div>
  <div className="mt-7 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 rounded-xl border border-slate-800 bg-slate-900 p-1">{([["departments","Departments"],["courses","Courses"],["subjects","Subjects"]] as [Tab,string][]).map(([k,t])=><button key={k} onClick={()=>{setTab(k);setShowForm(false)}} className={`rounded-lg px-4 py-2 text-sm ${tab===k?"bg-blue-600 text-white":"text-slate-400 hover:bg-slate-800 hover:text-white"}`}>{t}</button>)}</div><div className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab}...`} className={`${inputClass} md:w-64`}/><button onClick={add} className="whitespace-nowrap rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500">+ Add {label}</button></div></div>
  {showForm&&<form onSubmit={submit} className="mt-5 rounded-2xl border border-blue-500/20 bg-slate-900 p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-semibold">Add {label}</h2><button type="button" onClick={()=>setShowForm(false)} className="text-slate-400 hover:text-white">Cancel</button></div><div className="grid gap-4 md:grid-cols-2">
    {tab==="departments"&&<><Field label="Name"><input required className={inputClass} value={department.name} onChange={e=>setDepartment({...department,name:e.target.value})}/></Field><Field label="Code"><input required className={inputClass} value={department.code} onChange={e=>setDepartment({...department,code:e.target.value})}/></Field><Field label="Description"><input className={inputClass} value={department.description} onChange={e=>setDepartment({...department,description:e.target.value})}/></Field></>}
    {tab==="courses"&&<><Field label="Department"><select required className={inputClass} value={course.departmentId} onChange={e=>setCourse({...course,departmentId:e.target.value})}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name} ({d.code})</option>)}</select></Field><Field label="Course name"><input required className={inputClass} value={course.name} onChange={e=>setCourse({...course,name:e.target.value})}/></Field><Field label="Code"><input required className={inputClass} value={course.code} onChange={e=>setCourse({...course,code:e.target.value})}/></Field><Field label="Duration (years)"><input required min="1" type="number" className={inputClass} value={course.duration} onChange={e=>setCourse({...course,duration:e.target.value})}/></Field></>}
    {tab==="subjects"&&<><Field label="Course"><select required className={inputClass} value={subject.courseId} onChange={e=>setSubject({...subject,courseId:e.target.value})}><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select></Field><Field label="Subject name"><input required className={inputClass} value={subject.name} onChange={e=>setSubject({...subject,name:e.target.value})}/></Field><Field label="Code"><input required className={inputClass} value={subject.code} onChange={e=>setSubject({...subject,code:e.target.value})}/></Field><Field label="Credits"><input required min="1" type="number" className={inputClass} value={subject.credits} onChange={e=>setSubject({...subject,credits:e.target.value})}/></Field><Field label="Semester"><select className={inputClass} value={subject.semester} onChange={e=>setSubject({...subject,semester:e.target.value})}>{semesters.map(s=><option key={s} value={s}>{s.replace("_"," ")}</option>)}</select></Field><Field label="Description"><input className={inputClass} value={subject.description} onChange={e=>setSubject({...subject,description:e.target.value})}/></Field></>}
  </div><div className="mt-6 flex justify-end"><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2.5 font-semibold hover:bg-blue-500 disabled:opacity-50">{saving?"Saving...":"Save"}</button></div></form>}
  <div className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">{loading?<div className="p-12 text-center text-slate-400">Loading...</div>:tab==="departments"?<Departments data={ds}/>:tab==="courses"?<Courses data={cs}/>:<Subjects data={ss}/>}</div>
</div></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm"><span className="mb-2 block text-slate-300">{label}</span>{children}</label>}
function Departments({data}:{data:Department[]}){return data.length?<div className="divide-y divide-slate-800">{data.map(d=><div key={d.id} className="flex items-center justify-between px-6 py-5 hover:bg-slate-800/30"><div><p className="font-semibold">{d.name}</p><p className="text-sm text-slate-500">{d.description||"No description"}</p></div><span className="rounded-full bg-blue-500/10 px-4 py-1.5 text-sm text-blue-400">{d.code}</span></div>)}</div>:<Empty text="No departments found."/>}
function Courses({data}:{data:Course[]}){return data.length?<div className="divide-y divide-slate-800">{data.map(c=><div key={c.id} className="flex items-center justify-between px-6 py-5 hover:bg-slate-800/30"><div><p className="font-semibold">{c.name}</p><p className="text-sm text-slate-500">{c.department?.name||"Department unavailable"}</p></div><div className="flex gap-2"><span className="rounded-full bg-purple-500/10 px-3 py-1.5 text-sm text-purple-400">{c.code}</span><span className="rounded-full bg-slate-800 px-3 py-1.5 text-sm text-slate-300">{c.duration} years</span></div></div>)}</div>:<Empty text="No courses found."/>}
function Subjects({data}:{data:Subject[]}){return data.length?<div className="divide-y divide-slate-800">{data.map(s=><div key={s.id} className="flex items-center justify-between px-6 py-5 hover:bg-slate-800/30"><div><p className="font-semibold">{s.name}</p><p className="text-sm text-slate-500">{s.course?.name||"Course unavailable"}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-green-500/10 px-3 py-1.5 text-sm text-green-400">{s.code}</span><span className="rounded-full bg-blue-500/10 px-3 py-1.5 text-sm text-blue-400">{s.credits} credits</span><span className="rounded-full bg-slate-800 px-3 py-1.5 text-sm text-slate-300">{s.semester.replace("_"," ")}</span></div></div>)}</div>:<Empty text="No subjects found."/>}
function Empty({text}:{text:string}){return <div className="p-12 text-center text-slate-500">{text}</div>}
